### ISSUE TITLE
[Release Task] Deploy Azure App Service: XML Substitution unable to parse config

### ISSUE THREAD

**Issue by degant** [Microsoft/vsts-tasks#3970]
Reopening the issue #3575 since I cannot reopen the original issue. The issue is still not fixed and I'm still seeing same stack trace after trying latest 3.1.0 version. I've already shared the web.config file and root-cause shared was the presence of the tag 'constructor' in the web.config file. 

In the release task for azure app service deployment using the 3.0 template (in preview), the newly added XML substitution isn't able to parse the web.config.

Task: https://github.com/Microsoft/vsts-tasks/tree/master/Tasks/AzureRmWebAppDeployment

Here's the trace from the release logs after enabling system.debug:
Initiated variable substitution in config file : E:\agent_work\r69\a\temp_web_package_1627581922803074\Content\C\agent_work\157\s\src\project\obj\Release\Package\PackageTmp\Web.config
Detecting file encoding using BOM
Unable to parse file : E:\agent_work\r69\a\temp_web_package_1627581922803074\Content\C\agent_work\157\s\src\project\obj\Release\Package\PackageTmp\Web.config
TypeError: listOfNodes.push is not a function

Task Version:
Task : Azure App Service Deploy
Description : Update Azure App Service using Web Deploy / Kudu REST APIs
Version : 3.1.0

**Comment by vincentdass** [comment]
@degant , sorry for the issue you re facing.
#3775 , the issue is fixed in 3.1.2 version of the task and the fix will be avaiable in a week or two.

**Comment by degant** [comment]
Hi @vincentdass thanks for the follow-up. I'm afraid the last time I ran it was still 3.1.0. Will check again in a week or two and confirm. Appreciate all your help, thanks!

**Comment by vincentdass** [comment]
@degant,  deployments were completed in all the region's. Can you please queue a release and verify the task ?

**Comment by degant** [comment]
Hi @vincentdass. Can confirm that the fix is working fine with the 3.2.1 version. Thanks for all the help! 👍
